### ISSUE TITLE
About Preprocess

### ISSUE THREAD

**Issue by Feng-Xu97** [AmirSh15/Compact_SER#2]
Could you please release the script that how to preprocess the database of MSP-improv?

**Comment by AmirSh15** [comment]
Hi Feng,

I uploaded the code 'Feature_extraction_Opensmile_MSP.py' in the preprocessing dir. Let me know if you counter any problem.

**Comment by Feng-Xu97** [comment]
thanks!! I've learned a lot from your paper.

**Comment by AmirSh15** [comment]
Oh happy to hear that. You can also check our next work [here](https://ieeexplore.ieee.org/abstract/document/9354543).

**Comment by xlzhou01** [comment]
> Could you please release the script that how to preprocess the database of MSP-improv?
Hello, how to obtain the MSP-improv dataset? I don't know how to download this dataset?
